[versions]
kotlin = "1.7.10"  # Note: Plugin versions must be updated in the settings.gradle.kts too

kord-extensions = "1.5.5-SNAPSHOT"
kx-ser = "1.3.2"
logging = "2.1.21"
logback = "1.2.5"
jsoup = "1.15.2"


[libraries]
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
